import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme, Container, Section, ThemePanel } from "@radix-ui/themes";
import CartProvider from "@/components/shopify/CartProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
          <Theme>
          
        <CartProvider>
            <Section>
              <Container>{children}</Container>
            </Section>
        </CartProvider>
          </Theme>
      </body>
    </html>
  );
}
